name: toolbox

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '34 8 * * 2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: mortenlj/mise-lib/.github/workflows/setup.yaml@main

  build:
    permissions:
      packages: write
      checks: write
      pull-requests: write
    needs: setup
    uses: mortenlj/mise-lib/.github/workflows/build-docker.yaml@main
    with:
      main-image: ghcr.io/${{ github.repository }}
      clean-version: ${{ fromJSON(needs.setup.outputs.clean-version) }}
      tool-versions: ${{ needs.setup.outputs.tool-versions }}
    secrets:
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    permissions:
      packages: write
    needs: build
    uses: mortenlj/mise-lib/.github/workflows/cleanup.yaml@main
